In [28]:
import torch 
import torch.nn as nn

In [29]:
#Input

inputs = torch.tensor([1.0, 2.0, 3.0])

In [30]:
neuron = nn.Linear(in_features=3, out_features=1)

In [31]:
output = neuron(inputs)

In [32]:
output

tensor([0.6854], grad_fn=<ViewBackward0>)

In [33]:
#Verify...using direct formula
neuron.weight @ inputs + neuron.bias


tensor([0.6854], grad_fn=<AddBackward0>)

In [34]:
neuron.bias

Parameter containing:
tensor([0.0732], requires_grad=True)